### ISSUE TITLE
Autoupdater bei beta factory-update deaktiviert

### ISSUE THREAD

**Issue by sbschuermann** [freifunk-bingen/site-ffbin#2]
Nach einem Rescue Flash via tftp mit dem aktuellen beta-0.2 war der autoupdater deaktiviert. Eine entsprechende default Einstellung habe ich bisher nirgends finden können.

**Comment by kokel** [comment]
Siehe dazu http://gluon.readthedocs.org/en/v2015.1.1/features/autoupdater.html#building-images

```
By default, the autoupdater is disabled (as it is usually not helpful to have unexpected updates during development), but it can be enabled by setting the variable GLUON_BRANCH when building to override the default branch set in the set in the site configuration.
```
