### ISSUE TITLE
NTP + Firmware Mirror

### ISSUE THREAD

**Issue by kokel** [freifunk-bingen/site-ffbin#3]
Ihr habt in eurer site.conf des beta branches NTP-Server + Firmware Mirror angegeben, die nicht direkt im Mesh erreicht werden können.

Bedenkt, dass die Knoten _nur_ IPv6 Adressen haben und _nur_ per IPv6 Dienste direkt ansprechen können. Im MWU-Netz gibt es noch kein öffentliches IPv6 also können eure Knoten die von euch angegebenen NTP-Server nicht erreichen. Auch der Autoupdater wird über die von euch angegebene URL keine neuen Firmware-Images laden können.

**Comment by sbschuermann** [comment]
Danke für den Hinweis!

Autoupdate funktioniert, weil firmware.freifunk-bingen.de nur nach ipv4 auflöst, ntp-server werde ich nochmal austesten, ggfs erstmal auch hier eure eintragen!

**Comment by kokel** [comment]
Bist du dir mit den Autoupdates wirklich sicher?
Die Knoten kommen per IPv4 nicht ins Internet, weil die keine routbare IPv4 Adresse haben.

**Comment by sbschuermann** [comment]
Habe ich schon ausgetestet und läuft. Das hiesse dann ja wohl, das der autoupdater über das Interface im LAN läuft. Muss ich mir nochmal genau anschauen.

**Comment by sbschuermann** [comment]
Nochmal bestätigt: autoupdater und ntp laufen (via shell auf next-node). Sowohl firmware.freifunk-bingen.de als auch 0.pool.ntp.org... liefern nur ipv4-Adressen zurück. Muss also über die wan-bridge laufen..

**Comment by kokel** [comment]
Ja, mir wurde das auch grad nochmal im gluon channels bestätigt. Problem bleibt aber bei mesh-only Knoten, die haben keinen Uplink um diese Destinationen zu erreichen.

**Comment by sbschuermann** [comment]
Wir sind gerade am rätseln; auch firmware.freifunk-mwu.de löst nur nach ipv4 und "öffentlichen" ipv6 auf - keine ipv6 aus dem FFMWU-Netz

**Comment by manuelfischer** [comment]
Ich habe das jetzt mal mit einem zweiten mesh-only Knoten getestet, IPv4 kann er tatsächlich nicht.
So ganz verstehe ich euer DNS-Setup nicht. Habt ihr einfach für ffmz.org auf den Gateways neue Zonen angelegt, welche die "öffentlichen" übersteuern?
Hieße ja dann, dass wir auf euren Gateways auch eine eigene Zone bräuchten

**Comment by kokel** [comment]
Also in Gluon wird bewusst auf IPv4-Funktionalität der Knoten verzichtet und alles per IPv6 gemacht, das ist kein Bug, sondern bewusst konfiguriert. IPv4 ist eben ein legacy Protokoll.

Alles, was für die Knoten selbst wichtig ist sollte sowieso intern aus dem Freifunk-Netz erreichbar sein, weil man ja so unabhängig vom Internet sein will wie es geht.

Am Besten ihr hängt eine VM für eure Sachen direkt ins Freifunk-Netz. Das kann eine Kiste an einem Client Port eines Knotens sein oder auch ne VM im Internet, die wie die Knoten auch ein VPN über fastd ins Freifunk Netz aufbauen, darüber Batman/Alfred sprechen. Auf der Kiste könnt ihr dann eure Firmwares bereitstellen, einen NTP Server laufen lassen, etc.

Thema DNS:
Viele Freifunk Communities nutzen eigene TLDs wie z.B. .ffpb oder .ffhl oder .ffda
Wir wollten das nicht, weil wir darauf keine SSL Zertifikate ausstellen lassen können von z.B. Cacert/StartSSL etc. und nutzen deshalb intern "öffentliche" Domains ffmz.org und ffwi.org.
Die nutzen wir ausschließlich "intern".  Nach außen sind das lediglich Alias-Domains für freifunk-mainz.de bzw. freifunk-wiesbaden.de. Von daher wird da nichts übersteuert.

Euch würde ich das folgende Szenario vorschlagen:

Ihr nimmt z.B. .ffbin oder auch eine öffentliche wie z.B. ffbin.org/de/etc. was noch frei ist und betreibt auf eurem "Dienste"-Server einen Master DNS Server. Wir konfigurieren eure Zone dann bei uns als Slave. Dann habt ihr die volle Kontrolle über euer DNS und die Knoten+Clients können trotzdem eure Domain intern auflösen.

**Comment by kokel** [comment]
@sbschuermann firmware.freifunk-mwu.de nutzen wir nur im Internet.

Die Knoten haben "firmware.ffwi.org" bzw. "firmware.ffmz.org" für den Autoupdater konfiguriert, die nur intern erreichbar  und per IPv6 ULA erreichbar sind.

**Comment by manuelfischer** [comment]
@kokel Okay, bedeutet also wir müssen unser Gateway ("mettbroetchen") via fastd in euer Netz einbringen und dort die Firmware-Updates und ntp bereitstellen. Wir müssten euch dann unseren fastd public-key schicken, den ihr in eurem "peers-ffmz" eintragt, damit mettbroetchen im FF-Netz erreichbar ist.

Bedeutet auch, unser Gateway braucht eine statische IPv6 (und IPv4?) aus eurem Netzwerk.

Dann legen wir auf mettbroetchen noch unsere Zone an, die ihr auf euren Nameservern delegiert (ob jetz .ffbin oder sonstwas überlegen wir uns noch).

Hab ich das alles richtig verstanden? Wäre das für euch machbar / in Ordnung? Unser Gateway fungiert in dem Szenario noch nicht als Gateway, dafür brauchen wir noch ein Weilchen.

**Comment by manuelfischer** [comment]
Falls das in Ordnung wäre hier der fastd-Public-Key:
`2af95ea4f845132fdbef61b9629db3934c159306ace5dffdde21c0bbdc1784bf` ;)
Dann bräuchten wir nur noch von euch die Info, welche IPs wir uns vergeben können.

**Comment by kokel** [comment]
Der Vollständigkeit wegen auch hier nochmal wie auf der Maschinenraum Liste besprochen, die IPs:

IPv4: 10.37.1.12
IPv6: fd56:b4dc:4b1e::a25:10c

**Comment by sbschuermann** [comment]
Danke erstmal, GW gehen wir morgen an. Vorläufig haben wir eine funktionierende Config, sollte auch via mesh updaten, wenn wir das gateway am Laufen haben.
